name: Deploy to AWS

on:
  push:
    branches:
      - develop
    paths:
      - 'front-reload/**' 

permissions:
  contents: write
  actions: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Verify file structure
        run: ls -R

      - name: Set working directory
        run: cd reload-front
        shell: bash

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --production
        working-directory: ./reload-front

      - name: Build application
        run: |
          CI=false npm run build
        working-directory: ./reload-front


      - name: Create deployment package
        run: |
          zip -qq -r build.zip build appspec.yml deploy.sh
        shell: bash
        working-directory: ./reload-front

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: |
          aws s3 cp build.zip s3://refresh-f5-bucket/build.zip
        working-directory: ./reload-front

      - name: Deploy with CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name F5 \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name f5-codedeploy-group \
            --s3-location bucket=refresh-f5-bucket,bundleType=zip,key=build.zip
        working-directory: ./reload-front
